### ISSUE TITLE
Pygame window

### ISSUE THREAD

**Issue by L-i-n-u-x-C-a-t** [anat3000/Gravit#7]
Donc : quand on lance la simulation rien n'apparait. (voir file1.png) Mais quand on essaye de fermer le pygame, une boule de couleur (bleu ou gris) s'affiche a l'écran et la fenètre ne se ferme pas. (voir file2.png)
![file1](https://user-images.githubusercontent.com/46047705/71412837-b4741600-264f-11ea-8039-05c2d28ca4d3.png)
![file2](https://user-images.githubusercontent.com/46047705/71412838-b50cac80-264f-11ea-99e6-d1d18d578611.png)

**Comment by L-i-n-u-x-C-a-t** [comment]
ah et c'est quoi le "avant" qui s'affiche dans la console?

**Comment by anat3000** [comment]
Pour le 1er, petite erreur d'identation, le cercle ne s'affichait que lorsque le programme se stoppait.
Pour le 2e, le bug était dû à une ligne print qui aurait dû être supprimée après la phase de test des méthodes play, pause et stop de la classe gravit.simulation.Simulation
Merci @L-i-n-u-x-C-a-t !

**Comment by anat3000** [comment]
Le 2e bug est résolu !

**Comment by anat3000** [comment]
Le 1er bug est résolu ! Je ferme le pb !
